from __future__ import annotations

# Generated by scripts/generate_desktop_contract.py. Do not edit by hand.

DESKTOP_CONTRACT_SOURCE = "codex-desktop-decompiled/native-binaries/codex.strings.txt"
DESKTOP_CONTRACT_SOURCE_VERSION = "26.527.31326"
DESKTOP_CONTRACT_SOURCE_SHA256 = "2c8f09822e0b42a40af0f1e58c719803797e544748ccbcb328e32c2ace295418"

DESKTOP_RESPONSE_ITEM_TYPES = frozenset((
    "message",
    "reasoning",
    "local_shell_call",
    "function_call",
    "tool_search_call",
    "function_call_output",
    "custom_tool_call",
    "custom_tool_call_output",
    "tool_search_output",
    "web_search_call",
    "image_generation_call",
    "compaction",
    "compaction_trigger",
    "context_compaction",
    "other",
))

SHIM_EXTRA_RESPONSE_INPUT_TYPES = frozenset((
    "input_text",
    "text",
    "input_image",
    "input_audio",
    "computer_call_output",
    "mcp_tool_call",
    "mcp_tool_call_output",
))

DESKTOP_WEB_SEARCH_ACTION_TYPES = frozenset((
    "search",
    "open_page",
    "find_in_page",
))

DESKTOP_WEB_SEARCH_ACTION_FIELDS = {
    "search": frozenset(('query', 'queries')),
    "open_page": frozenset(('url',)),
    "find_in_page": frozenset(('pattern',)),
}

DESKTOP_LOCAL_SHELL_ACTION_FIELDS = frozenset((
    "command",
    "timeout_ms",
    "working_directory",
    "env",
    "user",
))

DESKTOP_IMAGE_GENERATION_ACTION_FIELDS = frozenset((
    "prompt",
    "revised_prompt",
))

DESKTOP_THREAD_SETTINGS_FIELDS = frozenset((
    "approvalsReviewer",
    "sandboxPolicy",
    "activePermissionProfile",
    "serviceTier",
    "effort",
    "collaborationMode",
    "personality",
))

DESKTOP_THREAD_START_PARAM_FIELDS = frozenset((
    "serviceName",
    "sessionStartSource",
    "dynamicTools",
    "mockExperimentalField",
    "experimentalRawEvents",
))
