#!/usr/bin/env python3
"""Generate codex_shim/desktop_app_server_contract.py from Desktop RE artifacts."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from scripts.desktop_re_common import (  # noqa: E402
    parse_desktop_http_endpoints,
    parse_model_provider_wire_fields,
    parse_rpc_methods,
    parse_thread_settings_fields,
    parse_thread_start_param_fields,
    schemas_dir,
    source_version,
    strings_sha256,
    strings_text,
)
from codex_shim.desktop_decompiled import codex_strings_path, require_available  # noqa: E402

OUTPUT_PATH = ROOT / "codex_shim" / "desktop_app_server_contract.py"


def _render_tuple(values: tuple[str, ...], *, indent: str = "    ") -> str:
    return "\n".join(f'{indent}"{value}",' for value in values)


def _rpc_methods_from_schema(schemas_path: Path) -> tuple[str, ...] | None:
    if not schemas_path.is_file():
        return None
    payload = json.loads(schemas_path.read_text(encoding="utf-8"))
    methods: set[str] = set()

    def walk(node: object) -> None:
        if isinstance(node, dict):
            for key, value in node.items():
                if key in {"method", "notification"} and isinstance(value, str) and "/" in value:
                    methods.add(value)
                walk(value)
        elif isinstance(node, list):
            for item in node:
                walk(item)

    walk(payload)
    return tuple(sorted(methods)) if methods else None


def _render_contract() -> str:
    text = strings_text()
    fallback = schemas_dir() / "app_server_fallback_index.json"
    v2_schema = schemas_dir() / "codex_app_server_protocol.v2.schemas.json"

    rpc_methods = _rpc_methods_from_schema(v2_schema)
    extraction_method = "v2_json_schema"
    if rpc_methods is None and fallback.is_file():
        index = json.loads(fallback.read_text(encoding="utf-8"))
        rpc_methods = tuple(index.get("rpc_methods", ()))
        extraction_method = "strings_fallback_index"
    if rpc_methods is None:
        rpc_methods = parse_rpc_methods(text)
        extraction_method = "strings_glued_methods"
    elif fallback.is_file() and not v2_schema.is_file():
        extraction_method = "strings_fallback_index"

    thread_settings_fields = parse_thread_settings_fields(text)
    thread_start_fields = parse_thread_start_param_fields(text)
    model_provider_fields = parse_model_provider_wire_fields(text)
    http_endpoints = parse_desktop_http_endpoints(text)

    return f'''from __future__ import annotations

# Generated by scripts/generate_desktop_app_server_contract.py. Do not edit by hand.

DESKTOP_APP_SERVER_CONTRACT_SOURCE = "codex-desktop-decompiled/native-binaries/codex.strings.txt"
DESKTOP_APP_SERVER_CONTRACT_SOURCE_VERSION = "{source_version()}"
DESKTOP_APP_SERVER_CONTRACT_SOURCE_SHA256 = "{strings_sha256()}"
DESKTOP_APP_SERVER_RPC_EXTRACTION = "{extraction_method}"

APP_SERVER_RPC_METHODS = frozenset((
{_render_tuple(rpc_methods)}
))

THREAD_SETTINGS_FIELDS = frozenset((
{_render_tuple(thread_settings_fields)}
))

THREAD_START_PARAM_FIELDS = frozenset((
{_render_tuple(thread_start_fields)}
))

MODEL_PROVIDER_WIRE_FIELDS = frozenset((
{_render_tuple(model_provider_fields)}
))

DESKTOP_HTTP_ENDPOINTS = frozenset((
{_render_tuple(http_endpoints)}
))
'''


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--write", action="store_true")
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args(argv)

    if not codex_strings_path().is_file():
        message = f"Desktop strings dump not found: {codex_strings_path()}"
        if args.check and not require_available():
            print(f"skip app-server contract check ({message})", file=sys.stderr)
            return 0
        print(message, file=sys.stderr)
        return 1

    generated = _render_contract()
    if args.write:
        OUTPUT_PATH.write_text(generated)
        return 0
    if args.check:
        try:
            current = OUTPUT_PATH.read_text()
        except FileNotFoundError:
            current = ""
        if current != generated:
            print(
                f"{OUTPUT_PATH} is stale; run scripts/generate_desktop_app_server_contract.py --write",
                file=sys.stderr,
            )
            return 1
        return 0
    print(generated)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
