#!/usr/bin/env python3
from __future__ import annotations

import argparse
import hashlib
import re
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from codex_shim.desktop_decompiled import (  # noqa: E402
    codex_strings_path,
    provenance_readme,
    require_available,
)

STRINGS_PATH = codex_strings_path()
README_PATH = provenance_readme()
OUTPUT_PATH = ROOT / "codex_shim" / "desktop_contract.py"

SHIM_EXTRA_RESPONSE_INPUT_TYPES = (
    "input_text",
    "text",
    "input_image",
    "input_audio",
    "computer_call_output",
    "mcp_tool_call",
    "mcp_tool_call_output",
)

WEB_SEARCH_ACTION_FIELDS = {
    "search": ("query", "queries"),
    "open_page": ("url",),
    "find_in_page": ("pattern",),
}

LOCAL_SHELL_ACTION_FIELDS = ("command", "timeout_ms", "working_directory", "env", "user")
IMAGE_GENERATION_ACTION_FIELDS = ("prompt", "revised_prompt")


def _source_version() -> str:
    text = README_PATH.read_text()
    match = re.search(r"\| Bundle version \| ([^|]+) \|", text)
    return match.group(1).strip() if match else "unknown"


def _response_item_types(text: str) -> tuple[str, ...]:
    start = text.find("ResponseItem.ts")
    end = text.find("FileChange.ts", start)
    if start < 0 or end < 0:
        raise SystemExit("Could not locate ResponseItem.ts segment in Desktop strings.")
    segment = text[start:end]
    values = re.findall(r'"type": "([a-z_]+)"', segment)
    if not values:
        raise SystemExit("Could not extract ResponseItem type tags from Desktop strings.")
    return tuple(dict.fromkeys(values))


def _web_search_action_types(text: str) -> tuple[str, ...]:
    matches = list(re.finditer("WebSearchAction\\.ts", text))
    start = matches[-1].start() if matches else -1
    end = text.find("RealtimeVoice.ts", start)
    if start < 0 or end < 0:
        raise SystemExit("Could not locate WebSearchAction.ts segment in Desktop strings.")
    segment = text[start:end]
    values = re.findall(r'"type": "([a-z_]+)"', segment)
    if not values:
        raise SystemExit("Could not extract WebSearchAction type tags from Desktop strings.")
    return tuple(dict.fromkeys(values))


def _image_generation_action_fields(text: str) -> tuple[str, ...]:
    if "image_generation_call" not in text:
        raise SystemExit("Could not locate image_generation_call in Desktop strings.")
    missing = [field for field in IMAGE_GENERATION_ACTION_FIELDS if field not in text]
    if missing:
        raise SystemExit(f"Desktop strings missing ImageGeneration action fields: {sorted(missing)}")
    return IMAGE_GENERATION_ACTION_FIELDS


def _render_tuple(values: tuple[str, ...], *, indent: str = "    ") -> str:
    return "\n".join(f'{indent}"{value}",' for value in values)


def _render_contract() -> str:
    text = STRINGS_PATH.read_text(errors="replace")
    source_hash = hashlib.sha256(STRINGS_PATH.read_bytes()).hexdigest()
    response_item_types = _response_item_types(text)
    web_search_action_types = _web_search_action_types(text)
    image_generation_action_fields = _image_generation_action_fields(text)
    missing_actions = set(WEB_SEARCH_ACTION_FIELDS) - set(web_search_action_types)
    if missing_actions:
        raise SystemExit(f"Desktop strings are missing expected WebSearchAction variants: {sorted(missing_actions)}")
    extras = tuple(value for value in SHIM_EXTRA_RESPONSE_INPUT_TYPES if value not in response_item_types)
    return f'''from __future__ import annotations

# Generated by scripts/generate_desktop_contract.py. Do not edit by hand.

DESKTOP_CONTRACT_SOURCE = "codex-desktop-decompiled/native-binaries/codex.strings.txt"
DESKTOP_CONTRACT_SOURCE_VERSION = "{_source_version()}"
DESKTOP_CONTRACT_SOURCE_SHA256 = "{source_hash}"

DESKTOP_RESPONSE_ITEM_TYPES = frozenset((
{_render_tuple(response_item_types)}
))

SHIM_EXTRA_RESPONSE_INPUT_TYPES = frozenset((
{_render_tuple(extras)}
))

DESKTOP_WEB_SEARCH_ACTION_TYPES = frozenset((
{_render_tuple(web_search_action_types)}
))

DESKTOP_WEB_SEARCH_ACTION_FIELDS = {{
{chr(10).join(f'    "{key}": frozenset(({", ".join(repr(value) for value in fields)}{"," if len(fields) == 1 else ""})),'
              for key, fields in WEB_SEARCH_ACTION_FIELDS.items())}
}}

DESKTOP_LOCAL_SHELL_ACTION_FIELDS = frozenset((
{_render_tuple(LOCAL_SHELL_ACTION_FIELDS)}
))

DESKTOP_IMAGE_GENERATION_ACTION_FIELDS = frozenset((
{_render_tuple(image_generation_action_fields)}
))
'''


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--write", action="store_true", help="Rewrite codex_shim/desktop_contract.py.")
    parser.add_argument("--check", action="store_true", help="Fail if the generated contract is stale.")
    args = parser.parse_args(argv)
    if not STRINGS_PATH.is_file():
        message = f"Desktop strings dump not found: {STRINGS_PATH}"
        if args.check and not require_available():
            print(f"skip contract regen check ({message})", file=sys.stderr)
            return 0
        print(message, file=sys.stderr)
        return 1
    generated = _render_contract()
    if args.write:
        OUTPUT_PATH.write_text(generated)
        return 0
    if args.check:
        try:
            current = OUTPUT_PATH.read_text()
        except FileNotFoundError:
            current = ""
        if current != generated:
            print(f"{OUTPUT_PATH} is stale; run scripts/generate_desktop_contract.py --write", file=sys.stderr)
            return 1
        return 0
    print(generated)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
