#!/usr/bin/env python3
"""Mine shim-relevant symbols from extracted Desktop Electron bundles."""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from codex_shim.desktop_decompiled import app_asar_extracted_dir, desktop_decompiled_root  # noqa: E402

PATTERNS: tuple[tuple[str, re.Pattern[str]], ...] = (
    ("wire_api", re.compile(r"wire_api")),
    ("base_url", re.compile(r"base_url")),
    ("modelProvider", re.compile(r"modelProvider")),
    ("responses-api", re.compile(r"responses-api[-\w]*")),
    ("loopback", re.compile(r"127\.0\.0\.1(?::\d+)?")),
    ("devApiBaseUrl", re.compile(r"devApiBaseUrl")),
    ("prodApiBaseUrl", re.compile(r"prodApiBaseUrl")),
    ("custom_model_catalog", re.compile(r"custom_model_catalog")),
    ("http_local", re.compile(r"http://127\.0\.0\.1[^\s\"']*")),
)

SCAN_DIRS = (
    ".vite/build",
    "webview/assets",
)


def _scan_file(path: Path) -> list[dict[str, object]]:
    try:
        text = path.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return []
    hits: list[dict[str, object]] = []
    for label, pattern in PATTERNS:
        for match in pattern.finditer(text):
            start = max(0, match.start() - 80)
            end = min(len(text), match.end() + 80)
            hits.append(
                {
                    "pattern": label,
                    "match": match.group(0),
                    "file": str(path),
                    "context": text[start:end].replace("\n", " "),
                }
            )
    return hits


def _render_markdown(hits: list[dict[str, object]]) -> str:
    lines = [
        "# Desktop Electron mining (shim-relevant)",
        "",
        "Auto-generated by `scripts/mine_desktop_electron.py`. Do not edit by hand.",
        "",
    ]
    by_pattern: dict[str, list[dict[str, object]]] = {}
    for hit in hits:
        by_pattern.setdefault(str(hit["pattern"]), []).append(hit)
    for pattern in sorted(by_pattern):
        lines.append(f"## {pattern}")
        lines.append("")
        for hit in by_pattern[pattern][:25]:
            lines.append(f"- `{hit['file']}`: `{hit['match']}`")
            lines.append(f"  - `{hit['context']}`")
        if len(by_pattern[pattern]) > 25:
            lines.append(f"- … {len(by_pattern[pattern]) - 25} more")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser()
    parser.parse_args(argv)

    asar_root = app_asar_extracted_dir()
    if not asar_root.is_dir():
        print(f"skip electron mining (missing {asar_root})", file=sys.stderr)
        return 0

    hits: list[dict[str, object]] = []
    for rel in SCAN_DIRS:
        base = asar_root / rel
        if not base.is_dir():
            continue
        for path in sorted(base.rglob("*.js")):
            hits.extend(_scan_file(path))

    out_json = desktop_decompiled_root() / "extracted" / "electron_mining.json"
    out_md = desktop_decompiled_root() / "DESKTOP_RE_FINDINGS.md"
    out_json.parent.mkdir(parents=True, exist_ok=True)
    out_json.write_text(json.dumps({"hits": hits}, indent=2) + "\n", encoding="utf-8")
    out_md.write_text(_render_markdown(hits), encoding="utf-8")
    print(f"wrote {out_json} ({len(hits)} hits)")
    print(f"wrote {out_md}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
