#!/usr/bin/env python3
"""Summarize Ghidra decompilation output for shim-relevant symbols."""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from codex_shim.desktop_decompiled import desktop_decompiled_root  # noqa: E402

SHIM_KEYWORDS = (
    "responses-api-proxy",
    "backend-api",
    "ModelProvider",
    "wire_api",
    "/v1/responses",
    "chatgpt.com",
    "OpenAI-Beta",
    "thread_config",
    "app-server",
)


def _ghidra_root() -> Path:
    return desktop_decompiled_root() / "ghidra" / "codex"


def _scan_decomp(decomp_dir: Path) -> list[dict[str, str]]:
    hits: list[dict[str, str]] = []
    if not decomp_dir.is_dir():
        return hits
    pattern = re.compile("|".join(re.escape(k) for k in SHIM_KEYWORDS), re.IGNORECASE)
    for path in sorted(decomp_dir.glob("**/*.c")):
        try:
            text = path.read_text(encoding="utf-8", errors="replace")
        except OSError:
            continue
        if not pattern.search(text):
            continue
        matched = sorted({m.group(0) for m in pattern.finditer(text)})
        hits.append({"file": str(path.relative_to(_ghidra_root())), "keywords": ", ".join(matched)})
    return hits


def _scan_strings_facts(facts_dir: Path) -> list[dict[str, str]]:
    path = facts_dir / "strings.json"
    if not path.is_file():
        return []
    payload = json.loads(path.read_text(encoding="utf-8"))
    rows = payload if isinstance(payload, list) else payload.get("strings", [])
    hits: list[dict[str, str]] = []
    for row in rows:
        value = str(row.get("string") or row.get("value") or "")
        if not value:
            continue
        if not any(keyword.lower() in value.lower() for keyword in SHIM_KEYWORDS):
            continue
        hits.append(
            {
                "address": str(row.get("address") or row.get("addr") or ""),
                "string": value[:240],
            }
        )
    return hits[:200]


def _render_markdown(decomp_hits: list[dict[str, str]], string_hits: list[dict[str, str]]) -> str:
    lines = [
        "# Ghidra shim hits",
        "",
        "Auto-generated by `scripts/summarize_ghidra_shim_hits.py`.",
        "",
        f"## Decompiled functions ({len(decomp_hits)})",
        "",
    ]
    for hit in decomp_hits[:150]:
        lines.append(f"- `{hit['file']}` — {hit['keywords']}")
    if len(decomp_hits) > 150:
        lines.append(f"- … {len(decomp_hits) - 150} more")
    lines.extend(["", f"## String facts ({len(string_hits)})", ""])
    for hit in string_hits[:80]:
        addr = hit["address"]
        prefix = f"`{addr}` " if addr else ""
        lines.append(f"- {prefix}`{hit['string']}`")
    if len(string_hits) > 80:
        lines.append(f"- … {len(string_hits) - 80} more")
    return "\n".join(lines).rstrip() + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser()
    args = parser.parse_args(argv)

    root = _ghidra_root()
    decomp_hits = _scan_decomp(root / "decomp-rust" / "functions")
    string_hits = _scan_strings_facts(root / "facts")
    out = root / "shim_hits.md"
    out.write_text(_render_markdown(decomp_hits, string_hits), encoding="utf-8")
    print(f"wrote {out} ({len(decomp_hits)} decomp, {len(string_hits)} strings)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
